import {
  type ActorKind,
  type AssetRecord,
  type EntityMeta,
  type ProductionProject,
  ProductionProjectSchema,
  type TimelineClip,
} from "./schema";

const SEEDED_AT = "2026-08-26T16:00:00.000Z";
const SEEDED_REVISION = 1;

const meta = (
  id: string,
  status: EntityMeta["status"] = "approved",
  derivedFrom: string[] = [],
  locked = false,
  authoredBy: ActorKind = "codex",
): EntityMeta => ({
  id,
  revisionCreated: SEEDED_REVISION,
  revisionUpdated: SEEDED_REVISION,
  authoredBy,
  lastEditedBy: authoredBy,
  locked,
  status,
  derivedFrom,
});

const imageAsset = (
  id: string,
  sceneId: string,
  name: string,
  description: string,
  palette: string,
): AssetRecord => ({
  meta: meta(id, "approved", [sceneId]),
  kind: "image",
  name,
  description,
  currentVersionId: `${id}_v1`,
  versions: [
    {
      id: `${id}_v1`,
      version: 1,
      status: "approved",
      uri: `/media/fax-oracle-corridor.png?asset=${id}&palette=${palette}`,
      mimeType: "image/png",
      width: 1672,
      height: 941,
      createdAt: SEEDED_AT,
      provider: "praxis-seed",
      model: "art-directed-placeholder",
      prompt: description,
      costUsd: 0,
    },
  ],
  tags: ["fax-oracle", "previz", "institutional"],
  pinned: true,
});

const sceneClip = (
  number: number,
  startFrame: number,
  durationFrames: number,
  status: EntityMeta["status"] = "approved",
): TimelineClip => {
  const suffix = String(number).padStart(2, "0");
  const sceneId = `scene_${suffix}`;
  const assetId = `asset_scene_${suffix}`;
  return {
    meta: meta(`clip_scene_${suffix}`, status, [sceneId, assetId]),
    kind: "scene",
    name: `Scene ${suffix}`,
    startFrame,
    durationFrames,
    sourceStartFrame: 0,
    sourceDurationFrames: durationFrames,
    sceneId,
    assetId,
    assetVersionId: `${assetId}_v1`,
    versionPolicy: "pinned",
    opacity: 1,
    transform: { x: 0, y: 0, scale: 1, rotation: 0 },
    transitionIn: number === 1 ? undefined : "dissolve-8f",
    transitionOut: number === 5 ? "fade-to-black-12f" : undefined,
  };
};

/**
 * A deterministic, fully linked 25-second project used by the first vertical slice.
 * Callers receive a fresh parsed object on every invocation.
 */
export const createSeedProject = (): ProductionProject =>
  ProductionProjectSchema.parse({
    schemaVersion: "0.1",
    projectId: "project_fax_oracle",
    revision: SEEDED_REVISION,
    metadata: {
      title: "The Fax Oracle",
      tagline: "The future still arrives on thermal paper.",
      description:
        "A 25-second institutional trailer for an obsolete machine that answers tomorrow's questions.",
      fps: 30,
      frameSize: { width: 1920, height: 1080 },
      aspectRatio: "16:9",
      durationFrames: 750,
      createdAt: SEEDED_AT,
      updatedAt: SEEDED_AT,
    },
    brief: {
      premise:
        "In an empty civic building, a fax machine quietly receives answers from the near future.",
      objective: "Introduce the Fax Oracle as credible, uncanny institutional infrastructure.",
      audience: "Design- and technology-literate viewers who enjoy dry speculative fiction.",
      tone: ["institutional", "restrained", "uncanny", "deadpan"],
      targetDurationFrames: 750,
      callToAction: "Ask a better question.",
    },
    style: {
      visualDirection:
        "Fluorescent municipal interiors, severe centered framing, dusty cream paper, and one signal-red accent.",
      palette: ["#ECE8DC", "#16191C", "#B9C5BD", "#E34832"],
      typography: ["Inter Variable", "Roboto Condensed Variable"],
      motionLanguage: ["slow push-in", "hard typographic cut", "paper-feed micro-motion"],
      audioDirection: "Room tone, electrical hum, relay clicks, and a calm public-information voice.",
    },
    script: {
      beats: [
        {
          meta: meta("beat_01"),
          order: 0,
          title: "The premise",
          startFrame: 0,
          durationFrames: 135,
          narration: "The machine has been waiting for a question.",
          visualIntent: "An empty fluorescent corridor. A fax machine waits at the vanishing point.",
          deliveryCue: "Quiet authority; leave air after ‘waiting’.",
          enhancementCues: ["fluorescent ballast hum"],
          sourceRefs: [],
        },
        {
          meta: meta("beat_02"),
          order: 1,
          title: "The signal",
          startFrame: 135,
          durationFrames: 135,
          narration: "Not from the office. From eleven minutes ahead.",
          visualIntent: "The telephone relay wakes. The machine's green status lamp becomes the hero.",
          deliveryCue: "Factual, never conspiratorial.",
          enhancementCues: ["relay click", "dial tone fragment"],
          sourceRefs: [],
        },
        {
          meta: meta("beat_03"),
          order: 2,
          title: "The proof",
          startFrame: 270,
          durationFrames: 165,
          narration: "Every answer arrives before anyone remembers asking.",
          visualIntent: "Thermal paper curls into frame with an impossible timestamp.",
          deliveryCue: "Land ‘before’ without melodrama.",
          enhancementCues: ["paper feed", "date-stamp impact"],
          sourceRefs: [],
        },
        {
          meta: meta("beat_04"),
          order: 3,
          title: "The institution",
          startFrame: 435,
          durationFrames: 150,
          narration: "A public service for decisions that cannot wait.",
          visualIntent: "Austere service diagram labels INPUT, DELAY, and REPLY.",
          deliveryCue: "Public-information cadence.",
          enhancementCues: ["subtle terminal chirps"],
          sourceRefs: [],
        },
        {
          meta: meta("beat_05"),
          order: 4,
          title: "The invitation",
          startFrame: 585,
          durationFrames: 165,
          narration: "The Fax Oracle. Ask a better question.",
          visualIntent: "The answer sheet stops beneath the mark. Cut to black before it can be read.",
          deliveryCue: "Warm, concise, final.",
          enhancementCues: ["mechanical stop", "room tone tail"],
          sourceRefs: [],
        },
      ],
    },
    scenes: [
      {
        meta: meta("scene_01", "approved", ["beat_01"]),
        beatId: "beat_01",
        order: 0,
        title: "The waiting corridor",
        narrativeRole: "Establish the impossible machine as ordinary infrastructure.",
        informationRole: "Location and premise",
        visualDescription: "Symmetrical municipal corridor with a lone beige fax machine at the far end.",
        shotIntent: "Make the machine feel small but inevitable.",
        cameraLanguage: "Locked wide, almost imperceptible push-in.",
        estimatedDurationFrames: 150,
        requiredAssetIds: ["asset_scene_01"],
        heroMoment: false,
      },
      {
        meta: meta("scene_02", "approved", ["beat_02"]),
        beatId: "beat_02",
        order: 1,
        title: "Eleven minutes",
        narrativeRole: "Reveal the time displacement without spectacle.",
        informationRole: "Mechanism",
        visualDescription: "Macro detail of the green ready lamp and a red digital clock reflected in plastic.",
        shotIntent: "Let one mundane indicator carry the reveal.",
        cameraLanguage: "Clinical macro, shallow focus shift from clock to lamp.",
        estimatedDurationFrames: 135,
        requiredAssetIds: ["asset_scene_02"],
        heroMoment: false,
      },
      {
        meta: meta("scene_03", "approved", ["beat_03"], true, "director"),
        beatId: "beat_03",
        order: 2,
        title: "The impossible receipt",
        narrativeRole: "Provide tactile proof and the film's iconic image.",
        informationRole: "Evidence",
        visualDescription: "Cream thermal paper loops toward camera. Its timestamp is eleven minutes ahead.",
        shotIntent: "Make obsolete paper feel oracular.",
        cameraLanguage: "Overhead close-up with slow paper-feed motion.",
        estimatedDurationFrames: 165,
        requiredAssetIds: ["asset_scene_03"],
        heroMoment: true,
      },
      {
        meta: meta("scene_04", "stale", ["beat_04"]),
        beatId: "beat_04",
        order: 3,
        title: "Civic diagram",
        narrativeRole: "Normalize the phenomenon through institutional language.",
        informationRole: "Service explanation",
        visualDescription: "A severe cream-and-black systems diagram animated with one red signal line.",
        shotIntent: "Explain just enough to deepen the joke.",
        cameraLanguage: "Flat graphic composition; stepped reveal.",
        estimatedDurationFrames: 135,
        requiredAssetIds: ["asset_scene_04"],
        heroMoment: false,
      },
      {
        meta: meta("scene_05", "approved", ["beat_05"]),
        beatId: "beat_05",
        order: 4,
        title: "Ask a better question",
        narrativeRole: "Resolve on an invitation while preserving the mystery.",
        informationRole: "Brand and call to action",
        visualDescription: "Answer sheet under a restrained wordmark; the printed answer remains just out of frame.",
        shotIntent: "End before explanation becomes possible.",
        cameraLanguage: "Centered product close-up, then hard cut to black.",
        estimatedDurationFrames: 165,
        requiredAssetIds: ["asset_scene_05"],
        heroMoment: true,
      },
    ],
    assets: {
      asset_scene_01: imageAsset(
        "asset_scene_01",
        "scene_01",
        "Empty corridor plate",
        "A centered empty municipal corridor with a beige fax machine at the vanishing point.",
        "cream",
      ),
      asset_scene_02: imageAsset(
        "asset_scene_02",
        "scene_02",
        "Ready lamp macro",
        "Macro photograph of a green ready lamp with a red digital clock reflection.",
        "green-red",
      ),
      asset_scene_03: {
        ...imageAsset(
          "asset_scene_03",
          "scene_03",
          "Impossible receipt",
          "Overhead cream thermal-paper receipt carrying an impossible future timestamp.",
          "cream-red",
        ),
        pinned: true,
      },
      asset_scene_04: {
        ...imageAsset(
          "asset_scene_04",
          "scene_04",
          "Service diagram",
          "Institutional information diagram showing INPUT, DELAY, and REPLY.",
          "black-cream-red",
        ),
        meta: meta("asset_scene_04", "stale", ["scene_04"]),
        versions: [
          {
            id: "asset_scene_04_v1",
            version: 1,
            status: "stale",
            uri: "/media/fax-oracle-corridor.png?asset=asset_scene_04&palette=black-cream-red",
            mimeType: "image/png",
            width: 1672,
            height: 941,
            createdAt: SEEDED_AT,
            provider: "praxis-seed",
            model: "art-directed-placeholder",
            prompt: "Institutional information diagram showing INPUT, DELAY, and REPLY.",
            costUsd: 0,
          },
        ],
      },
      asset_scene_05: imageAsset(
        "asset_scene_05",
        "scene_05",
        "Oracle end card",
        "Fax paper beneath a restrained Fax Oracle wordmark on near-black.",
        "black-cream",
      ),
      asset_narration: {
        meta: meta("asset_narration", "approved", ["beat_01", "beat_02", "beat_03", "beat_04", "beat_05"]),
        kind: "audio",
        name: "Provisional narration",
        description: "Deterministic provisional voice track for the animatic.",
        currentVersionId: "asset_narration_v1",
        versions: [
          {
            id: "asset_narration_v1",
            version: 1,
            status: "approved",
            uri: "seed://fax-oracle/narration.wav",
            mimeType: "audio/wav",
            durationFrames: 750,
            createdAt: SEEDED_AT,
            provider: "praxis-seed",
            costUsd: 0,
          },
        ],
        tags: ["voice", "previz"],
        pinned: false,
      },
      asset_music: {
        meta: meta("asset_music", "approved", ["project_fax_oracle"]),
        kind: "music",
        name: "Municipal current",
        description: "A low electrical pulse and restrained analog drone beneath the full animatic.",
        currentVersionId: "asset_music_v1",
        versions: [
          {
            id: "asset_music_v1",
            version: 1,
            status: "approved",
            uri: "seed://fax-oracle/municipal-current.wav",
            mimeType: "audio/wav",
            durationFrames: 750,
            createdAt: SEEDED_AT,
            provider: "praxis-seed",
            costUsd: 0,
          },
        ],
        tags: ["music", "underscore", "previz"],
        pinned: true,
      },
    },
    timeline: {
      meta: meta("timeline_main"),
      fps: 30,
      durationFrames: 750,
      tracks: [
        {
          meta: meta("track_video_01"),
          name: "Scenes",
          kind: "video",
          order: 0,
          muted: false,
          solo: false,
          clips: [
            sceneClip(1, 0, 150),
            sceneClip(2, 150, 135),
            sceneClip(3, 285, 165),
            sceneClip(4, 450, 135, "stale"),
            sceneClip(5, 585, 165),
          ],
        },
        {
          meta: meta("track_overlay_01"),
          name: "Titles",
          kind: "overlay",
          order: 1,
          muted: false,
          solo: false,
          clips: [
            {
              meta: meta("clip_title_01", "approved", ["beat_05"]),
              kind: "text",
              name: "Fax Oracle wordmark",
              startFrame: 625,
              durationFrames: 105,
              sourceStartFrame: 0,
              versionPolicy: "pinned",
              opacity: 1,
              transform: { x: 0, y: 0, scale: 1, rotation: 0 },
              text: "THE FAX ORACLE",
              textStyle: {
                fontFamily: "Roboto Condensed Variable",
                fontSizePx: 86,
                fontWeight: 700,
                fontStyle: "normal",
                color: "#ECE8DC",
                textAlign: "center",
                lineHeight: 1,
                letterSpacingPx: 8,
              },
              transitionIn: "fade-8f",
            },
          ],
        },
        {
          meta: meta("track_audio_01"),
          name: "Narration",
          kind: "audio",
          order: 2,
          muted: false,
          solo: false,
          clips: [
            {
              meta: meta("clip_narration_01", "approved", ["asset_narration"]),
              kind: "audio",
              name: "Provisional narration",
              startFrame: 0,
              durationFrames: 750,
              sourceStartFrame: 0,
              sourceDurationFrames: 750,
              assetId: "asset_narration",
              assetVersionId: "asset_narration_v1",
              versionPolicy: "pinned",
              opacity: 1,
              transform: { x: 0, y: 0, scale: 1, rotation: 0 },
              gainDb: 0,
            },
          ],
        },
        {
          meta: meta("track_audio_02"),
          name: "Music",
          kind: "audio",
          order: 3,
          muted: false,
          solo: false,
          clips: [
            {
              meta: meta("clip_music_01", "approved", ["asset_music"]),
              kind: "music",
              name: "Municipal current",
              startFrame: 0,
              durationFrames: 750,
              sourceStartFrame: 0,
              sourceDurationFrames: 750,
              assetId: "asset_music",
              assetVersionId: "asset_music_v1",
              versionPolicy: "pinned",
              opacity: 0.32,
              transform: { x: 0, y: 0, scale: 1, rotation: 0 },
              gainDb: -10,
              transitionOut: "fade-30f",
            },
          ],
        },
      ],
    },
    stages: {
      treatment: { name: "treatment", status: "approved", revisionUpdated: 1, staleReasons: [], approvedAt: SEEDED_AT },
      script: { name: "script", status: "approved", revisionUpdated: 1, staleReasons: [], approvedAt: SEEDED_AT },
      previz: { name: "previz", status: "approved", revisionUpdated: 1, staleReasons: [], approvedAt: SEEDED_AT },
      assets: { name: "assets", status: "ready", revisionUpdated: 1, staleReasons: [] },
      edit: { name: "edit", status: "active", revisionUpdated: 1, staleReasons: [] },
      finish: { name: "finish", status: "pending", revisionUpdated: 1, staleReasons: [] },
    },
    delegation: {
      treatment: { stage: "treatment", mode: "act", maxSpendUsd: 0, checkpointAfterStage: true },
      script: { stage: "script", mode: "act", maxSpendUsd: 0, checkpointAfterStage: true },
      previz: { stage: "previz", mode: "propose", maxSpendUsd: 0, checkpointAfterStage: true },
      assets: { stage: "assets", mode: "act", maxSpendUsd: 1, checkpointAfterStage: false },
      edit: { stage: "edit", mode: "act", maxSpendUsd: 0, checkpointAfterStage: true },
      finish: { stage: "finish", mode: "propose", maxSpendUsd: 0, checkpointAfterStage: true },
    },
    decisions: [
      {
        meta: meta("decision_tighten_ending", "draft", ["beat_05"]),
        kind: "proposal",
        stage: "script",
        title: "Tighten the final line",
        summary: "Remove the product-name repetition and let the invitation land alone.",
        status: "pending",
        proposedBy: "codex",
        proposedAt: SEEDED_AT,
        proposedOperations: [
          {
            type: "script.updateBeat",
            beatId: "beat_05",
            patch: { narration: "Ask a better question." },
          },
        ],
      },
    ],
    checkpoints: [
      {
        id: "checkpoint_seed",
        label: "Seeded rough cut",
        revision: 1,
        createdAt: SEEDED_AT,
        createdBy: "system",
        reason: "Deterministic reset point for the public demo.",
      },
    ],
    delivery: {
      container: "mp4",
      videoCodec: "h264",
      audioCodec: "aac",
      width: 1920,
      height: 1080,
      fps: 30,
      quality: "preview",
    },
  });
